version: '3'

services:
  # Next.js service
  myplanner:
    container_name: mynextjs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-mongodb-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://usertest:7roPAwscdreP4UaR@mongo:27017/adecco
    depends_on:
      - mongo
    links: 
      - mongo

  # MongoDB service
  mongo:
    container_name: mymongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usertest
      MONGO_INITDB_ROOT_PASSWORD: 7roPAwscdreP4UaR
      MONGO_INITDB_DATABASE: adecco
  
    volumes:
      - mongodb-data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


volumes:
  mongodb-data:



